In [9]:
import pandas as pd
df_cour = pd.read_csv("coursera_courses.csv")
df_cour_rev = pd.read_csv("coursera_reviews.csv")

In [10]:
df_cour.head()

   Unnamed: 0                institution                       course_id
0           0        stanford university                machine learning
1           1      university of alberta               indigenous canada
2           2            yale university       the science of well being
3           3                     google  technical support fundamentals
4           4  google - spectrum sharing        google cbrs cpi training

In [11]:
df_cour_rev.head()

,Unnamed: 0,date_reviews,rating,course_id,reviews,reviewers,year,month
0,0,2020-02-12,medium,google cbrs cpi training,pretty dry but i was able to pass with just tw...,robert s,2020,2
1,1,2020-09-28,medium,google cbrs cpi training,would be a better experience if the video and ...,gabriel e r,2020,9
2,2,2020-04-08,medium,google cbrs cpi training,information was perfect the program itself was...,jacob d,2020,4
3,3,2020-02-24,medium,google cbrs cpi training,a few grammatical mistakes on test made me do ...,dale b,2020,2
4,4,2020-06-18,medium,google cbrs cpi training,excellent course and the training provided was...,sean g,2020,6

In [12]:
#merge two dataframes
df_cour= pd.merge(df_cour_rev,df_cour,on="course_id", how= 'left')

In [13]:
df_cour.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 519891 entries, 0 to 519890
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Unnamed: 0_x  519891 non-null  int64
 1   date_reviews  519891 non-null  object
 2   rating        519891 non-null  object
 3   course_id     519891 non-null  object
 4   reviews       515552 non-null  object
 5   reviewers     519891 non-null  object
 6   year          519891 non-null  int64
 7   month         519891 non-null  int64
 8   Unnamed: 0_y  519891 non-null  int64
 9   institution   519891 non-null  object
dtypes: int64(4), object(6)
memory usage: 43.6+ MB

In [14]:
df_cour.head()
df_cour.drop(columns=["Unnamed: 0_x","Unnamed: 0_y"],inplace=True)

In [15]:
df_cour.head()

,date_reviews,rating,course_id,reviews,reviewers,year,month,institution
0,2020-02-12,medium,google cbrs cpi training,pretty dry but i was able to pass with just tw...,robert s,2020,2,google - spectrum sharing
1,2020-09-28,medium,google cbrs cpi training,would be a better experience if the video and ...,gabriel e r,2020,9,google - spectrum sharing
2,2020-04-08,medium,google cbrs cpi training,information was perfect the program itself was...,jacob d,2020,4,google - spectrum sharing
3,2020-02-24,medium,google cbrs cpi training,a few grammatical mistakes on test made me do ...,dale b,2020,2,google - spectrum sharing
4,2020-06-18,medium,google cbrs cpi training,excellent course and the training provided was...,sean g,2020,6,google - spectrum sharing

In [16]:
df_cour.to_csv("coursera.csv")